import { expect, test } from '@playwright/test';

test('test', async ({ page }) => {
await page.goto('https://hcms-web-ohc-hcms-dev.apps.ocp-dev.pegadaian.co.id/index');
await page.getByRole('textbox', { name: 'User code or email *' }).fill('Demoneuron');
await page.getByRole('textbox', { name: 'Password *' }).fill('standar');
await page.getByRole('button', { name: 'Login' }).click();
await page.goto('https://hcms-web-ohc-hcms-dev.apps.ocp-dev.pegadaian.co.id/index');
await page.getByRole('button', { name: '  Employee' }).click();
await page.getByRole('link', { name: ' Manage Employee' }).click();
await page.getByRole('searchbox', { name: 'Cari:' }).fill('siti aisiah');
await page.getByRole('button', { name: '' }).click();
await page.getByRole('link', { name: '  Pengaturan Golongan' }).click();
await page.getByRole('link', { name: ' Employee SK' }).click();
await page.getByRole('link', { name: '   Buat baru' }).click();
await page.locator('#document_no').fill('9119119');
await page.locator('#document_dtm').click();
await page.getByText('6', { exact: true }).first().click();
await page.locator('#form-employee div').filter({ hasText: 'Pegawai *' }).getByLabel('').click();
await page.locator('input[type="search"]').nth(4).fill('siti');
await page.getByRole('treeitem', { name: '[ P69890013 ] SITI AISIAH' }).click();
await page.locator('#start_date').click();
await page.getByText('6', { exact: true }).nth(1).click();
await page.locator('#select2-ohp_id-container').click();
await page.locator('input[type="search"]').nth(4).click();
await page.locator('input[type="search"]').nth(4).fill('m');
await page.getByRole('treeitem', { name: 'Manajer Operasional Usaha' }).first().click();
await page.getByLabel('', { exact: true }).nth(1).click();
await page.getByRole('treeitem', { name: 'Definitif' }).click();
await page.locator('#form-employee div').filter({ hasText: 'Tipe pekerjaan * DefinitifDefinitif Job Subtype *' }).getByLabel('', { exact: true }).click();
await page.getByRole('treeitem', { name: 'Definitif' }).click();
await page.getByRole('combobox').filter({ hasText: /^$/ }).click();
await page.getByRole('treeitem', { name: 'Grade 12' }).click();
await page.getByRole('button', { name: 'Tambah Karyawan' }).click();
await page.getByRole('button', { name: 'Simpan' }).click();
await page.getByRole('button', { name: 'Ya', exact: true }).click();
await page.getByRole('link', { name: ' Manage Employee' }).click();
await page.getByRole('searchbox', { name: 'Cari:' }).click();
await page.getByRole('searchbox', { name: 'Cari:' }).fill('siti aisiah');
await page.getByRole('button', { name: '' }).click();
await page.getByRole('link', { name: '  Pengaturan Golongan' }).click();
await expect(page.locator('#table-set-category_wrapper div').filter({ hasText: 'Tipe GolonganTipe' }).nth(1)).toBeVisible();
});